spring:
  application:
    name: libraryApi
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/database/database
    driverClassName: org.h2.Driver
    username: sa
    password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /

cacheEvictAll:
  cron: 0 0 0 * * ?